# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coba_tabel', models.CharField(max_length=200)),
            ],
        ),
    ]
