# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('notlp', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
